contact_links:
  - name: Questions and Help
    url: https://github.com/berstend/puppeteer-extra/wiki/Scraping-Chat
    about: This issue tracker is not for support questions. You can join our Discord server and ask the community for help.
